### PR TITLE
adding bibliography.yaml file

### LINKED ISSUE #17: Use Relaton for fetching inline bibliographic references
## Broken references inserted

concepts/concept-3.1.3.3.yaml
```yaml
  - content: Generalised Enterprise Reference Architecture and Methodologies (GERAM)
      [<<iso_std_iso_15704_en>>] is an architecture framework.
  - content: Reference Model of Open Distributed Processing (RM-ODP) [<<iso_std_iso_iec_10746_en>>]
      is an architecture framework.
```

Here, the `<<iso_std_iso_15704_en>>` type of notation is for references. It refers to the ISO 15704 standard, which is to be linked to the ISO website.

The method to resolve this is to use Relaton-ISO (`relaton-iso` gem) to fetch the metadata of "ISO 15704:2019", and then you can obtain the urn and the HTTPS link.

```ruby
> require 'relaton_iso'
> bib = RelatonIso::IsoBibliography.get 'ISO 15704:2019'
> bib.to_hash
=> 
{"id"=>"ISO15704-2019",
 "title"=>
  [{"type"=>"title-intro",
    "content"=>"Enterprise modelling and architecture",
    "language"=>["en"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"type"=>"title-main",
    "content"=>"Requirements for enterprise-referencing architectures and methodologies",
    "language"=>["en"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"type"=>"main",
    "content"=>
     "Enterprise modelling and architecture - Requirements for enterprise-referencing architectures and methodologies",
    "language"=>["en"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"type"=>"title-intro",
    "content"=>"Modélisation et architecture d'entreprise",
    "language"=>["fr"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"type"=>"title-main",
    "content"=>"Exigences pour les architectures et les méthodologies de référencement d'entreprise",
    "language"=>["fr"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"type"=>"main",
    "content"=>
     "Modélisation et architecture d'entreprise - Exigences pour les architectures et les méthodologies de référencement d'entreprise",
    "language"=>["fr"],
    "script"=>["Latn"],
    "format"=>"text/plain"}],
 "link"=>
  [{"content"=>"https://www.iso.org/standard/71890.html", "type"=>"src"},
   {"content"=>"https://www.iso.org/obp/ui/#!iso:std:71890:en", "type"=>"obp"},
   {"content"=>"https://www.iso.org/contents/data/standard/07/18/71890.detail.rss", "type"=>"rss"}],
 "type"=>"standard",
 "docid"=>
  [{"id"=>"ISO 15704:2019", "type"=>"ISO", "primary"=>true},
   {"id"=>"urn:iso:std:iso:15704:stage-60.60:ed-2", "type"=>"URN"}],
 "docnumber"=>"15704",
 "date"=>[{"type"=>"published", "value"=>"2019-12"}],
 "contributor"=>
  [{"organization"=>
     {"name"=>["International Organization for Standardization"], "abbreviation"=>"ISO", "url"=>"www.iso.org"},
    "role"=>["publisher"]}],
 "edition"=>{"content"=>"2"},
 "revdate"=>"2019-12",
 "language"=>["en", "fr"],
 "script"=>["Latn"],
 "abstract"=>
  [{"content"=>
     "This document specifies a reference base of concepts and principles for enterprise architectures that enable enterprise development, enterprise integration, enterprise interoperability, human understanding and computer processing. This document further specifies requirements for models and languages created for expressing such enterprise architectures.\nThis document specifies those terms, concepts and principles considered necessary to address stakeholder concerns and to carry out enterprise creation programmes as well as any incremental change projects required by the enterprise throughout the whole life of the enterprise. This document forms the basis by which enterprise architecture and modelling standards can be developed or aligned.\nThis document does not define standard enterprises, standard organizational structures, standard enterprise processes, or standard enterprise data. In addition, this standard does not specify enterprise modelling processes.",
    "language"=>["en"],
    "script"=>["Latn"],
    "format"=>"text/plain"},
   {"content"=>
     "This document specifies a reference base of concepts and principles for enterprise architectures that enable enterprise development, enterprise integration, enterprise interoperability, human understanding and computer processing. This document further specifies requirements for models and languages created for expressing such enterprise architectures.\nThis document specifies those terms, concepts and principles considered necessary to address stakeholder concerns and to carry out enterprise creation programmes as well as any incremental change projects required by the enterprise throughout the whole life of the enterprise. This document forms the basis by which enterprise architecture and modelling standards can be developed or aligned.\nThis document does not define standard enterprises, standard organizational structures, standard enterprise processes, or standard enterprise data. In addition, this standard does not specify enterprise modelling processes.",
    "language"=>["fr"],
    "script"=>["Latn"],
    "format"=>"text/plain"}],
 "docstatus"=>{"stage"=>{"value"=>"60"}, "substage"=>{"value"=>"60"}},
 "copyright"=>[{"owner"=>[{"name"=>["ISO"]}], "from"=>"2019"}],
 "relation"=>
  [{"type"=>"obsoletes",
    "bibitem"=>
     {"id"=>"ISO15704-2000",
      "type"=>"standard",
      "docid"=>[{"id"=>"ISO 15704:2000", "type"=>"ISO", "primary"=>true}],
      "formattedref"=>{"content"=>"ISO 15704:2000", "format"=>"text/plain"}}},
   {"type"=>"obsoletes",
    "bibitem"=>
     {"id"=>"ISO15704-2000/Amd1-2005",
      "type"=>"standard",
      "docid"=>[{"id"=>"ISO 15704:2000/Amd 1:2005", "type"=>"ISO", "primary"=>true}],
      "formattedref"=>{"content"=>"ISO 15704:2000/Amd 1:2005", "format"=>"text/plain"}}}],
 "place"=>["Geneva"],
 "fetched"=>"2022-08-24",
 "doctype"=>"international-standard",
 "editorialgroup"=>
  {"technical_committee"=>
    [{"name"=>"Interoperability, integration, and architectures for enterprise systems and automation applications",
      "number"=>184,
      "type"=>"TC",
      "identifier"=>"ISO/TC 184/SC 5"}]},
 "ics"=>[{"code"=>"25.040.01", "text"=>"Industrial automation systems in general"}],
 "structuredidentifier"=>{"project_number"=>"ISO 15704", "type"=>"ISO"}}
```

We need to integrate this functionality into geolexica-server.

_Originally posted by @ronaldtse in https://github.com/geolexica/isotc204-glossary/issues/14#issuecomment-1225087199_

### PR DESCRIPTION
**Pull request by HassanAkbar**
Use `Relaton` for fetching inline bibliographic references.

[geolexica/isotc204.geolexica.org](https://github.com/geolexica/isotc204.geolexica.org) PR -> https://github.com/geolexica/isotc204.geolexica.org/pull/12
Geolexica Server PR -> https://github.com/geolexica/geolexica-server/pull/192

Screenshot 2022-09-15 at 4 48 14 PM

closes #17

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse I have a few approaches in mind for this. Let me know which one you think is a good fit

1. Use `relaton` to fill the links in the `bibliography.yaml` file now and use the file when rendering the content. 
2. When rendering the content use the file `bibliography.yaml` for converting references to `relaton supported format` and then use `relaton` to fetch the `URL` for reference.
3. Don't use the `bibliography.yaml` file instead replace the content with the `relaton supported format` now and use `relaton` when rendering the content to fetch the `URL`.

**Comment by ronaldtse** [comment]
I vote for approach 1 with a modification. Make Relaton part of the compilation process (the "concept dataset preparation" process, not when rendering the content).

1. There is a "concept dataset preparation" process. This "staticizes" the data of the concept dataset.
2. In that preparation process, we process `bibliography.yaml` , and obtain Relaton YAML files (each Relaton output provides a readable YAML file). These YAML files goes into a `bibliography/` folder of the prepared dataset. In the original source files, it only contains `bibliography.yaml` and does not have any Relaton information.
3. During build, use the Relaton YAML files to render links.

**Comment by HassanAkbar** [comment]
@ronaldtse While running `relaton` for the references in the script there are some `does not have a recognised prefix` errors as highlighted in the attached image. What should I do in case of those references?

Screenshot 2022-09-14 at 2 55 14 PM

**Comment by ronaldtse** [comment]
The references that cannot be resolved by Relaton needs to be either provided in the Relaton YAML format already, or just a plain text string as provided by the user.

**Comment by ronaldtse** [comment]
Also, prioritize the information provided by Relaton over the human-supplied text. Thanks.

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
